`timescale 1ns / 1ps
// ============================================================
//  Testbench for fir_filter
//  Input:  input.txt  - 512 lines, 4-bit binary (Q signed)
//                        Generated by notebook Section 11
//                        (square-wave stimulus, BITS=4, SCALE=7)
//  Output: save.data   - 512 lines, 12-bit binary filter output
//
//  Matches fir_filter parameter set:
//    N_TAPS = 25, N2 = 4, N_COEFF = 12, N3 = 12
// ============================================================
module tb;

    // ── Parameters matching the DUT ──────────────────────────────────────
    parameter N2 = 4;   // input bit width
    parameter N3 = 12;  // output bit width

    // ── Simulation signals ────────────────────────────────────────────────
    reg                    CLK;
    reg                    RST;
    reg                    Enable;
    reg  signed [N2-1 : 0] input_data;

    wire signed [N3-1 : 0] output_data;
    wire signed [N2-1 : 0] SampleT;

    // ── Stimulus memory: 512 samples ──────────────────────────────────────
    reg [N2-1 : 0] data [0:511];

    // ── File handle ───────────────────────────────────────────────────────
    integer k;
    integer File1;

    // ── DUT instantiation ─────────────────────────────────────────────────
    fir_filter #(
        .N_TAPS (25),
        .N2     (4),
        .N_COEFF(12),
        .N3     (12),
        .SHIFT(6)
    ) uut (
        .input_data  (input_data),
        .CLK         (CLK),
        .RST         (RST),
        .Enable      (Enable),
        .output_data (output_data),
        .SampleT     (SampleT)
    );

    // ── 20 ns clock (50 MHz) ─────────────────────────────────────────────
    initial CLK = 0;
    always #10 CLK = ~CLK;

    // ── Stimulus ──────────────────────────────────────────────────────────
    initial begin
        // Load binary input data (4-bit wide, 512 entries)
        $readmemb("input.txt", data);

        // Open output file
        File1 = $fopen("save.data", "w");
        if (File1 == 0) begin
            $display("ERROR: could not open save.data");
            $finish;
        end

        // Initialise control signals
        RST        = 1'b0;
        Enable     = 1'b0;
        input_data = 0;

        // Apply reset for 2 cycles
        @(negedge CLK); RST = 1'b1;
        @(negedge CLK);
        @(negedge CLK); RST = 1'b0;

        // Enable and feed first sample before the loop
        Enable     = 1'b1;
        input_data = data[0];

        // Feed remaining 511 samples, log output after each posedge
        for (k = 1; k < 512; k = k + 1) begin
            @(posedge CLK);
            #1; // let output settle after posedge
            $fdisplay(File1, "%012b", output_data);
            input_data = data[k];
        end

        // Capture the very last output
        @(posedge CLK);
        #1;
        $fdisplay(File1, "%012b", output_data);

        $fclose(File1);
        $display("[✓] Simulation complete - save.data written (512 entries).");
        $finish;
    end

    // ── Optional waveform dump ────────────────────────────────────────────
    initial begin
        $dumpfile("fir_filter_tb.vcd");
        $dumpvars(0, tb);
    end
endmodule